baseURL = "https://timurv.ru/"
languageCode = "en-us"
title = "Timur Vafin"
theme = "coder"

[params]
    author = "Timur Vafin"
    description = "Timur's personal website"

    hideCredits = true
    hideCopyright = true

# Social links
[[params.social]]
    name = "E-mail"
    weight = 1
    url = "mailto:me@timurv.ru"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/timurvafin/"

[[params.social]]
    name = "LinkedIn"
    weight = 1
    url = "https://ru.linkedin.com/in/timurv"

[[params.social]]
    name = "Telegram"
    weight = 1
    url = "https://t.me/joinchat/AAAAAEGtZASR8bz7GxQzlg"
